import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class DubstepTest {

    @Test
    void songDecoder() {
        assertEquals("ABC", Dubstep.songDecoder("WUBWUBABCWUB"));
        assertEquals("R L", Dubstep.songDecoder("RWUBWUBWUBLWUB"));
        assertEquals("WE ARE THE CHAMPIONS MY FRIEND", Dubstep.songDecoder("WUBWEWUBAREWUBWUBTHEWUBCHAMPIONSWUBMYWUBFRIENDWUB"));
    }
    @Test
    void stringExceed200Characters() {
        assertNull(Dubstep.songDecoder("WUBWEWUBAREWUBWUBTHEWUBCHAMPIONSWUBMYWUBFRIENDWUBWUBWEWUBAREWUBWUBTHEWUBCHAMPIONSWUBMYWUBFRIENDWUBWUBWEWUBAREWUBWUBTHEWUBCHAMPIONSWUBMYWUBFRIENDWUBWUBWEWUBAREWUBWUBTHEWUBCHAMPIONSWUBMYWUBFRIENDWUBWUBWEWUBAREWUBWUBTHEWUBCHAMPIONSWUBMYWUBFRIENDWUBWUBWEWUBAREWUBWUBTHEWUBCHAMPIONSWUBMYWUBFRIENDWUB"));
        assertNotNull(Dubstep.songDecoder("WUB"));
    }
}